### ISSUE TITLE
この記事を書いた人欄を設ける

### ISSUE THREAD

**Issue by thanks2music** [thanks2music/revenge#90]
### 概要

- 記事詳細の下部に「この記事を書いた人」欄を追加する

### こうしたい

- 各記事詳細の下部に「この記事を書いた人」欄がある
- 「この記事を書いた人」欄には以下の項目が存在する
  - アイコン
  - ニックネーム
  - 簡単なプロフィール
- ユーザー名(ニックネーム)は、そのユーザーが書いた記事一覧にリンクする

### 参考

![image](https://user-images.githubusercontent.com/953799/57969088-905fa080-79ad-11e9-9b25-66564d6958a3.png)

![image](https://user-images.githubusercontent.com/953799/57969103-fba97280-79ad-11e9-8ae4-74758358172e.png)

![image](https://user-images.githubusercontent.com/953799/57969049-15968580-79ad-11e9-8abb-ebc89a979124.png)

#### SP

![image](https://user-images.githubusercontent.com/953799/59824912-7bd84480-936d-11e9-983c-5e987b831421.png)

![image](https://user-images.githubusercontent.com/953799/59824955-94e0f580-936d-11e9-9315-da47a045da8b.png)

### 参考URL

- https://www.cinra.net/interview/201904-nakamurakaho

**Comment by ShunNagasue** [comment]
ライター欄調査
所感

- PCビューはおしゃれなところも多いがスマホビューだとどれも似通ったデザイン
- デザインはこの中で５が良い
- シンプル＋おしゃれは３
- この中には入れなかったがKAI-YOUがスマホビューでも一番いい気がする


1

https://ferret-plus.com/1858

![](https://paper-attachments.dropbox.com/s_AFDA3A9364C38E6D4689C86A1B36FD8AE2BE302253B3DB083B5E44D599E32CAE_1561008423817_+2019-06-20+14.26.18.png)


2

https://kiniblog.com/blog-manetaizu/

![](https://paper-attachments.dropbox.com/s_AFDA3A9364C38E6D4689C86A1B36FD8AE2BE302253B3DB083B5E44D599E32CAE_1561009019839_+2019-06-20+14.36.35.png)


3

https://liginc.co.jp/473809

![](https://paper-attachments.dropbox.com/s_AFDA3A9364C38E6D4689C86A1B36FD8AE2BE302253B3DB083B5E44D599E32CAE_1561009148918_+2019-06-20+14.38.00.png)


4

https://kurone43.com/shukyaku-monetize/

![](https://paper-attachments.dropbox.com/s_AFDA3A9364C38E6D4689C86A1B36FD8AE2BE302253B3DB083B5E44D599E32CAE_1561009321778_+2019-06-20+14.41.36.png)


5

https://wp-principle.net/start-wp/

![](https://paper-attachments.dropbox.com/s_AFDA3A9364C38E6D4689C86A1B36FD8AE2BE302253B3DB083B5E44D599E32CAE_1561009779324_+2019-06-20+14.49.27.png)
